#!/bin/bash

set -e

BASE=$(dirname "$0")
. $(dirname "$BASE")/common.sh

APTARGS=${APTARGS:---no-remove}

pkgs="$($BASE/check)"
[ -z "$pkgs" ] && exit

sudo DEBIAN_FRONTEND=noninteractive apt-get install -y $APTARGS --no-install-recommends $pkgs
